Update pre.yml

diff --git a/stages/pre.yml b/stages/pre.yml
--- a/stages/pre.yml
+++ b/stages/pre.yml
@@ -1,11 +1,12 @@
-commitmsg=$(git log --pretty=oneline --abbrev-commit | grep -m1 "Merge")
-cmt=${commitmsg:0:6}
-echo $cmt
-invalidcmt=$(git log --pretty=%B HEAD...$cmt | grep -v -e "FSP" | grep -v "Merge pull" | grep -v '^$')
-echo $invalidcmt
-echo "$(System.PullRequest.SourceBranch)"
-git log --pretty=%B HEAD...$cmt
-if [[ $invalidcmt -gt 0 ]]
-then
-    echo "Invalid Commit Message is found" && exit 1
-fi
+        steps:
+          - script: | 
+                     commitmsg=$(git log --pretty=oneline --abbrev-commit | grep -m1 "Merge pull")
+                     cmt=${commitmsg:0:6}
+                     invalidcmt=$(git log --pretty=%B HEAD...$cmt | grep -v -e "FSP" | grep -v "Merge" | grep -v '^$')
+                     echo $invalidcmt
+                     echo "$(System.PullRequest.SourceBranch)"
+                     git log --pretty=%B HEAD...$cmt
+                     if [[ $invalidcmt -gt 0 ]]
+                     then
+                        echo "Invalid Commit Message is found" && exit 1
+                     fi
